/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GlobalTableStatus;
import org.openapitools.client.model.ReplicaDescription;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GlobalTableDescription
 */
public class GlobalTableDescriptionTest {
    private final GlobalTableDescription model = new GlobalTableDescription();

    /**
     * Model tests for GlobalTableDescription
     */
    @Test
    public void testGlobalTableDescription() {
        // TODO: test GlobalTableDescription
    }

    /**
     * Test the property 'replicationGroup'
     */
    @Test
    public void replicationGroupTest() {
        // TODO: test replicationGroup
    }

    /**
     * Test the property 'globalTableArn'
     */
    @Test
    public void globalTableArnTest() {
        // TODO: test globalTableArn
    }

    /**
     * Test the property 'creationDateTime'
     */
    @Test
    public void creationDateTimeTest() {
        // TODO: test creationDateTime
    }

    /**
     * Test the property 'globalTableStatus'
     */
    @Test
    public void globalTableStatusTest() {
        // TODO: test globalTableStatus
    }

    /**
     * Test the property 'globalTableName'
     */
    @Test
    public void globalTableNameTest() {
        // TODO: test globalTableName
    }

}
