/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AutoScalingSettingsDescription;
import org.openapitools.client.model.IndexStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReplicaGlobalSecondaryIndexAutoScalingDescription
 */
public class ReplicaGlobalSecondaryIndexAutoScalingDescriptionTest {
    private final ReplicaGlobalSecondaryIndexAutoScalingDescription model = new ReplicaGlobalSecondaryIndexAutoScalingDescription();

    /**
     * Model tests for ReplicaGlobalSecondaryIndexAutoScalingDescription
     */
    @Test
    public void testReplicaGlobalSecondaryIndexAutoScalingDescription() {
        // TODO: test ReplicaGlobalSecondaryIndexAutoScalingDescription
    }

    /**
     * Test the property 'indexName'
     */
    @Test
    public void indexNameTest() {
        // TODO: test indexName
    }

    /**
     * Test the property 'indexStatus'
     */
    @Test
    public void indexStatusTest() {
        // TODO: test indexStatus
    }

    /**
     * Test the property 'provisionedReadCapacityAutoScalingSettings'
     */
    @Test
    public void provisionedReadCapacityAutoScalingSettingsTest() {
        // TODO: test provisionedReadCapacityAutoScalingSettings
    }

    /**
     * Test the property 'provisionedWriteCapacityAutoScalingSettings'
     */
    @Test
    public void provisionedWriteCapacityAutoScalingSettingsTest() {
        // TODO: test provisionedWriteCapacityAutoScalingSettings
    }

}
