package main

import (
	"github.com/amazon-dynamodb/mcp-server/config"
	"github.com/amazon-dynamodb/mcp-server/models"
	tools_x_amz_target_dynamodb_20120810_tagresource "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_tagresource"
	tools_x_amz_target_dynamodb_20120810_getitem "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_getitem"
	tools_x_amz_target_dynamodb_20120810_updatetimetolive "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updatetimetolive"
	tools_x_amz_target_dynamodb_20120810_transactgetitems "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_transactgetitems"
	tools_x_amz_target_dynamodb_20120810_describelimits "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describelimits"
	tools_x_amz_target_dynamodb_20120810_importtable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_importtable"
	tools_x_amz_target_dynamodb_20120810_batchexecutestatement "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_batchexecutestatement"
	tools_x_amz_target_dynamodb_20120810_batchwriteitem "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_batchwriteitem"
	tools_x_amz_target_dynamodb_20120810_enablekinesisstreamingdestination "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_enablekinesisstreamingdestination"
	tools_x_amz_target_dynamodb_20120810_executetransaction "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_executetransaction"
	tools_x_amz_target_dynamodb_20120810_describekinesisstreamingdestination "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describekinesisstreamingdestination"
	tools_x_amz_target_dynamodb_20120810_restoretablefrombackup "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_restoretablefrombackup"
	tools_x_amz_target_dynamodb_20120810_describecontributorinsights "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describecontributorinsights"
	tools_x_amz_target_dynamodb_20120810_batchgetitem "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_batchgetitem"
	tools_x_amz_target_dynamodb_20120810_putitem "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_putitem"
	tools_x_amz_target_dynamodb_20120810_updatetable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updatetable"
	tools_x_amz_target_dynamodb_20120810_untagresource "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_untagresource"
	tools_x_amz_target_dynamodb_20120810_updateglobaltable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updateglobaltable"
	tools_x_amz_target_dynamodb_20120810_updateglobaltablesettings "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updateglobaltablesettings"
	tools_x_amz_target_dynamodb_20120810_createbackup "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_createbackup"
	tools_x_amz_target_dynamodb_20120810_deletebackup "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_deletebackup"
	tools_x_amz_target_dynamodb_20120810_deletetable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_deletetable"
	tools_x_amz_target_dynamodb_20120810_updatetablereplicaautoscaling "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updatetablereplicaautoscaling"
	tools_x_amz_target_dynamodb_20120810_exporttabletopointintime "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_exporttabletopointintime"
	tools_x_amz_target_dynamodb_20120810_listbackups "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_listbackups"
	tools_x_amz_target_dynamodb_20120810_describeimport "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describeimport"
	tools_x_amz_target_dynamodb_20120810_describetimetolive "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describetimetolive"
	tools_x_amz_target_dynamodb_20120810_describetablereplicaautoscaling "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describetablereplicaautoscaling"
	tools_x_amz_target_dynamodb_20120810_updatecontinuousbackups "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updatecontinuousbackups"
	tools_x_amz_target_dynamodb_20120810_transactwriteitems "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_transactwriteitems"
	tools_x_amz_target_dynamodb_20120810_listcontributorinsights "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_listcontributorinsights"
	tools_x_amz_target_dynamodb_20120810_updatecontributorinsights "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updatecontributorinsights"
	tools_x_amz_target_dynamodb_20120810_describebackup "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describebackup"
	tools_x_amz_target_dynamodb_20120810_listimports "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_listimports"
	tools_x_amz_target_dynamodb_20120810_createglobaltable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_createglobaltable"
	tools_x_amz_target_dynamodb_20120810_disablekinesisstreamingdestination "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_disablekinesisstreamingdestination"
	tools_x_amz_target_dynamodb_20120810_describecontinuousbackups "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describecontinuousbackups"
	tools_x_amz_target_dynamodb_20120810_describeglobaltablesettings "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describeglobaltablesettings"
	tools_x_amz_target_dynamodb_20120810_listtagsofresource "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_listtagsofresource"
	tools_x_amz_target_dynamodb_20120810_query "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_query"
	tools_x_amz_target_dynamodb_20120810_describeexport "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describeexport"
	tools_x_amz_target_dynamodb_20120810_describeendpoints "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describeendpoints"
	tools_x_amz_target_dynamodb_20120810_createtable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_createtable"
	tools_x_amz_target_dynamodb_20120810_describeglobaltable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describeglobaltable"
	tools_x_amz_target_dynamodb_20120810_deleteitem "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_deleteitem"
	tools_x_amz_target_dynamodb_20120810_listglobaltables "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_listglobaltables"
	tools_x_amz_target_dynamodb_20120810_listexports "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_listexports"
	tools_x_amz_target_dynamodb_20120810_listtables "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_listtables"
	tools_x_amz_target_dynamodb_20120810_updateitem "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_updateitem"
	tools_x_amz_target_dynamodb_20120810_scan "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_scan"
	tools_x_amz_target_dynamodb_20120810_executestatement "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_executestatement"
	tools_x_amz_target_dynamodb_20120810_restoretabletopointintime "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_restoretabletopointintime"
	tools_x_amz_target_dynamodb_20120810_describetable "github.com/amazon-dynamodb/mcp-server/tools/x_amz_target_dynamodb_20120810_describetable"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_dynamodb_20120810_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_dynamodb_20120810_getitem.CreateGetitemTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updatetimetolive.CreateUpdatetimetoliveTool(cfg),
		tools_x_amz_target_dynamodb_20120810_transactgetitems.CreateTransactgetitemsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describelimits.CreateDescribelimitsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_importtable.CreateImporttableTool(cfg),
		tools_x_amz_target_dynamodb_20120810_batchexecutestatement.CreateBatchexecutestatementTool(cfg),
		tools_x_amz_target_dynamodb_20120810_batchwriteitem.CreateBatchwriteitemTool(cfg),
		tools_x_amz_target_dynamodb_20120810_enablekinesisstreamingdestination.CreateEnablekinesisstreamingdestinationTool(cfg),
		tools_x_amz_target_dynamodb_20120810_executetransaction.CreateExecutetransactionTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describekinesisstreamingdestination.CreateDescribekinesisstreamingdestinationTool(cfg),
		tools_x_amz_target_dynamodb_20120810_restoretablefrombackup.CreateRestoretablefrombackupTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describecontributorinsights.CreateDescribecontributorinsightsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_batchgetitem.CreateBatchgetitemTool(cfg),
		tools_x_amz_target_dynamodb_20120810_putitem.CreatePutitemTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updatetable.CreateUpdatetableTool(cfg),
		tools_x_amz_target_dynamodb_20120810_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updateglobaltable.CreateUpdateglobaltableTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updateglobaltablesettings.CreateUpdateglobaltablesettingsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_createbackup.CreateCreatebackupTool(cfg),
		tools_x_amz_target_dynamodb_20120810_deletebackup.CreateDeletebackupTool(cfg),
		tools_x_amz_target_dynamodb_20120810_deletetable.CreateDeletetableTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updatetablereplicaautoscaling.CreateUpdatetablereplicaautoscalingTool(cfg),
		tools_x_amz_target_dynamodb_20120810_exporttabletopointintime.CreateExporttabletopointintimeTool(cfg),
		tools_x_amz_target_dynamodb_20120810_listbackups.CreateListbackupsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describeimport.CreateDescribeimportTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describetimetolive.CreateDescribetimetoliveTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describetablereplicaautoscaling.CreateDescribetablereplicaautoscalingTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updatecontinuousbackups.CreateUpdatecontinuousbackupsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_transactwriteitems.CreateTransactwriteitemsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_listcontributorinsights.CreateListcontributorinsightsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updatecontributorinsights.CreateUpdatecontributorinsightsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describebackup.CreateDescribebackupTool(cfg),
		tools_x_amz_target_dynamodb_20120810_listimports.CreateListimportsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_createglobaltable.CreateCreateglobaltableTool(cfg),
		tools_x_amz_target_dynamodb_20120810_disablekinesisstreamingdestination.CreateDisablekinesisstreamingdestinationTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describecontinuousbackups.CreateDescribecontinuousbackupsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describeglobaltablesettings.CreateDescribeglobaltablesettingsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_listtagsofresource.CreateListtagsofresourceTool(cfg),
		tools_x_amz_target_dynamodb_20120810_query.CreateQueryTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describeexport.CreateDescribeexportTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describeendpoints.CreateDescribeendpointsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_createtable.CreateCreatetableTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describeglobaltable.CreateDescribeglobaltableTool(cfg),
		tools_x_amz_target_dynamodb_20120810_deleteitem.CreateDeleteitemTool(cfg),
		tools_x_amz_target_dynamodb_20120810_listglobaltables.CreateListglobaltablesTool(cfg),
		tools_x_amz_target_dynamodb_20120810_listexports.CreateListexportsTool(cfg),
		tools_x_amz_target_dynamodb_20120810_listtables.CreateListtablesTool(cfg),
		tools_x_amz_target_dynamodb_20120810_updateitem.CreateUpdateitemTool(cfg),
		tools_x_amz_target_dynamodb_20120810_scan.CreateScanTool(cfg),
		tools_x_amz_target_dynamodb_20120810_executestatement.CreateExecutestatementTool(cfg),
		tools_x_amz_target_dynamodb_20120810_restoretabletopointintime.CreateRestoretabletopointintimeTool(cfg),
		tools_x_amz_target_dynamodb_20120810_describetable.CreateDescribetableTool(cfg),
	}
}
