/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AutoScalingSettingsUpdate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents the auto scaling settings of a global secondary index for a global table that will be modified.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:20:21.724079+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GlobalSecondaryIndexAutoScalingUpdate {
  public static final String SERIALIZED_NAME_INDEX_NAME = "IndexName";
  @SerializedName(SERIALIZED_NAME_INDEX_NAME)
  @javax.annotation.Nullable
  private String indexName;

  public static final String SERIALIZED_NAME_PROVISIONED_WRITE_CAPACITY_AUTO_SCALING_UPDATE = "ProvisionedWriteCapacityAutoScalingUpdate";
  @SerializedName(SERIALIZED_NAME_PROVISIONED_WRITE_CAPACITY_AUTO_SCALING_UPDATE)
  @javax.annotation.Nullable
  private AutoScalingSettingsUpdate provisionedWriteCapacityAutoScalingUpdate;

  public GlobalSecondaryIndexAutoScalingUpdate() {
  }

  public GlobalSecondaryIndexAutoScalingUpdate indexName(@javax.annotation.Nullable String indexName) {
    this.indexName = indexName;
    return this;
  }

  /**
   * The name of the global secondary index.
   * @return indexName
   */
  @javax.annotation.Nullable
  public String getIndexName() {
    return indexName;
  }

  public void setIndexName(@javax.annotation.Nullable String indexName) {
    this.indexName = indexName;
  }


  public GlobalSecondaryIndexAutoScalingUpdate provisionedWriteCapacityAutoScalingUpdate(@javax.annotation.Nullable AutoScalingSettingsUpdate provisionedWriteCapacityAutoScalingUpdate) {
    this.provisionedWriteCapacityAutoScalingUpdate = provisionedWriteCapacityAutoScalingUpdate;
    return this;
  }

  /**
   * Get provisionedWriteCapacityAutoScalingUpdate
   * @return provisionedWriteCapacityAutoScalingUpdate
   */
  @javax.annotation.Nullable
  public AutoScalingSettingsUpdate getProvisionedWriteCapacityAutoScalingUpdate() {
    return provisionedWriteCapacityAutoScalingUpdate;
  }

  public void setProvisionedWriteCapacityAutoScalingUpdate(@javax.annotation.Nullable AutoScalingSettingsUpdate provisionedWriteCapacityAutoScalingUpdate) {
    this.provisionedWriteCapacityAutoScalingUpdate = provisionedWriteCapacityAutoScalingUpdate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalSecondaryIndexAutoScalingUpdate globalSecondaryIndexAutoScalingUpdate = (GlobalSecondaryIndexAutoScalingUpdate) o;
    return Objects.equals(this.indexName, globalSecondaryIndexAutoScalingUpdate.indexName) &&
        Objects.equals(this.provisionedWriteCapacityAutoScalingUpdate, globalSecondaryIndexAutoScalingUpdate.provisionedWriteCapacityAutoScalingUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(indexName, provisionedWriteCapacityAutoScalingUpdate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalSecondaryIndexAutoScalingUpdate {\n");
    sb.append("    indexName: ").append(toIndentedString(indexName)).append("\n");
    sb.append("    provisionedWriteCapacityAutoScalingUpdate: ").append(toIndentedString(provisionedWriteCapacityAutoScalingUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("IndexName", "ProvisionedWriteCapacityAutoScalingUpdate"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GlobalSecondaryIndexAutoScalingUpdate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GlobalSecondaryIndexAutoScalingUpdate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GlobalSecondaryIndexAutoScalingUpdate is not found in the empty JSON string", GlobalSecondaryIndexAutoScalingUpdate.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GlobalSecondaryIndexAutoScalingUpdate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GlobalSecondaryIndexAutoScalingUpdate` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("IndexName") != null && !jsonObj.get("IndexName").isJsonNull()) && !jsonObj.get("IndexName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `IndexName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("IndexName").toString()));
      }
      // validate the optional field `ProvisionedWriteCapacityAutoScalingUpdate`
      if (jsonObj.get("ProvisionedWriteCapacityAutoScalingUpdate") != null && !jsonObj.get("ProvisionedWriteCapacityAutoScalingUpdate").isJsonNull()) {
        AutoScalingSettingsUpdate.validateJsonElement(jsonObj.get("ProvisionedWriteCapacityAutoScalingUpdate"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GlobalSecondaryIndexAutoScalingUpdate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GlobalSecondaryIndexAutoScalingUpdate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GlobalSecondaryIndexAutoScalingUpdate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GlobalSecondaryIndexAutoScalingUpdate.class));

       return (TypeAdapter<T>) new TypeAdapter<GlobalSecondaryIndexAutoScalingUpdate>() {
           @Override
           public void write(JsonWriter out, GlobalSecondaryIndexAutoScalingUpdate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GlobalSecondaryIndexAutoScalingUpdate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GlobalSecondaryIndexAutoScalingUpdate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GlobalSecondaryIndexAutoScalingUpdate
   * @throws IOException if the JSON string is invalid with respect to GlobalSecondaryIndexAutoScalingUpdate
   */
  public static GlobalSecondaryIndexAutoScalingUpdate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GlobalSecondaryIndexAutoScalingUpdate.class);
  }

  /**
   * Convert an instance of GlobalSecondaryIndexAutoScalingUpdate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

