/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DestinationStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * KinesisStreamingDestinationOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:20:21.724079+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class KinesisStreamingDestinationOutput {
  public static final String SERIALIZED_NAME_TABLE_NAME = "TableName";
  @SerializedName(SERIALIZED_NAME_TABLE_NAME)
  @javax.annotation.Nullable
  private String tableName;

  public static final String SERIALIZED_NAME_STREAM_ARN = "StreamArn";
  @SerializedName(SERIALIZED_NAME_STREAM_ARN)
  @javax.annotation.Nullable
  private String streamArn;

  public static final String SERIALIZED_NAME_DESTINATION_STATUS = "DestinationStatus";
  @SerializedName(SERIALIZED_NAME_DESTINATION_STATUS)
  @javax.annotation.Nullable
  private DestinationStatus destinationStatus;

  public KinesisStreamingDestinationOutput() {
  }

  public KinesisStreamingDestinationOutput tableName(@javax.annotation.Nullable String tableName) {
    this.tableName = tableName;
    return this;
  }

  /**
   * The name of the table being modified.
   * @return tableName
   */
  @javax.annotation.Nullable
  public String getTableName() {
    return tableName;
  }

  public void setTableName(@javax.annotation.Nullable String tableName) {
    this.tableName = tableName;
  }


  public KinesisStreamingDestinationOutput streamArn(@javax.annotation.Nullable String streamArn) {
    this.streamArn = streamArn;
    return this;
  }

  /**
   * The ARN for the specific Kinesis data stream.
   * @return streamArn
   */
  @javax.annotation.Nullable
  public String getStreamArn() {
    return streamArn;
  }

  public void setStreamArn(@javax.annotation.Nullable String streamArn) {
    this.streamArn = streamArn;
  }


  public KinesisStreamingDestinationOutput destinationStatus(@javax.annotation.Nullable DestinationStatus destinationStatus) {
    this.destinationStatus = destinationStatus;
    return this;
  }

  /**
   * The current status of the replication.
   * @return destinationStatus
   */
  @javax.annotation.Nullable
  public DestinationStatus getDestinationStatus() {
    return destinationStatus;
  }

  public void setDestinationStatus(@javax.annotation.Nullable DestinationStatus destinationStatus) {
    this.destinationStatus = destinationStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KinesisStreamingDestinationOutput kinesisStreamingDestinationOutput = (KinesisStreamingDestinationOutput) o;
    return Objects.equals(this.tableName, kinesisStreamingDestinationOutput.tableName) &&
        Objects.equals(this.streamArn, kinesisStreamingDestinationOutput.streamArn) &&
        Objects.equals(this.destinationStatus, kinesisStreamingDestinationOutput.destinationStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tableName, streamArn, destinationStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KinesisStreamingDestinationOutput {\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    streamArn: ").append(toIndentedString(streamArn)).append("\n");
    sb.append("    destinationStatus: ").append(toIndentedString(destinationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("TableName", "StreamArn", "DestinationStatus"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to KinesisStreamingDestinationOutput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!KinesisStreamingDestinationOutput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in KinesisStreamingDestinationOutput is not found in the empty JSON string", KinesisStreamingDestinationOutput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!KinesisStreamingDestinationOutput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `KinesisStreamingDestinationOutput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("TableName") != null && !jsonObj.get("TableName").isJsonNull()) && !jsonObj.get("TableName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TableName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TableName").toString()));
      }
      if ((jsonObj.get("StreamArn") != null && !jsonObj.get("StreamArn").isJsonNull()) && !jsonObj.get("StreamArn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `StreamArn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("StreamArn").toString()));
      }
      // validate the optional field `DestinationStatus`
      if (jsonObj.get("DestinationStatus") != null && !jsonObj.get("DestinationStatus").isJsonNull()) {
        DestinationStatus.validateJsonElement(jsonObj.get("DestinationStatus"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!KinesisStreamingDestinationOutput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'KinesisStreamingDestinationOutput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<KinesisStreamingDestinationOutput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(KinesisStreamingDestinationOutput.class));

       return (TypeAdapter<T>) new TypeAdapter<KinesisStreamingDestinationOutput>() {
           @Override
           public void write(JsonWriter out, KinesisStreamingDestinationOutput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public KinesisStreamingDestinationOutput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of KinesisStreamingDestinationOutput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of KinesisStreamingDestinationOutput
   * @throws IOException if the JSON string is invalid with respect to KinesisStreamingDestinationOutput
   */
  public static KinesisStreamingDestinationOutput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, KinesisStreamingDestinationOutput.class);
  }

  /**
   * Convert an instance of KinesisStreamingDestinationOutput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

