/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BackupSummary;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListBackupsOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:20:21.724079+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ListBackupsOutput {
  public static final String SERIALIZED_NAME_BACKUP_SUMMARIES = "BackupSummaries";
  @SerializedName(SERIALIZED_NAME_BACKUP_SUMMARIES)
  @javax.annotation.Nullable
  private List<BackupSummary> backupSummaries;

  public static final String SERIALIZED_NAME_LAST_EVALUATED_BACKUP_ARN = "LastEvaluatedBackupArn";
  @SerializedName(SERIALIZED_NAME_LAST_EVALUATED_BACKUP_ARN)
  @javax.annotation.Nullable
  private String lastEvaluatedBackupArn;

  public ListBackupsOutput() {
  }

  public ListBackupsOutput backupSummaries(@javax.annotation.Nullable List<BackupSummary> backupSummaries) {
    this.backupSummaries = backupSummaries;
    return this;
  }

  public ListBackupsOutput addBackupSummariesItem(BackupSummary backupSummariesItem) {
    if (this.backupSummaries == null) {
      this.backupSummaries = new ArrayList<>();
    }
    this.backupSummaries.add(backupSummariesItem);
    return this;
  }

  /**
   * List of &lt;code&gt;BackupSummary&lt;/code&gt; objects.
   * @return backupSummaries
   */
  @javax.annotation.Nullable
  public List<BackupSummary> getBackupSummaries() {
    return backupSummaries;
  }

  public void setBackupSummaries(@javax.annotation.Nullable List<BackupSummary> backupSummaries) {
    this.backupSummaries = backupSummaries;
  }


  public ListBackupsOutput lastEvaluatedBackupArn(@javax.annotation.Nullable String lastEvaluatedBackupArn) {
    this.lastEvaluatedBackupArn = lastEvaluatedBackupArn;
    return this;
  }

  /**
   * &lt;p&gt; The ARN of the backup last evaluated when the current page of results was returned, inclusive of the current page of results. This value may be specified as the &lt;code&gt;ExclusiveStartBackupArn&lt;/code&gt; of a new &lt;code&gt;ListBackups&lt;/code&gt; operation in order to fetch the next page of results. &lt;/p&gt; &lt;p&gt; If &lt;code&gt;LastEvaluatedBackupArn&lt;/code&gt; is empty, then the last page of results has been processed and there are no more results to be retrieved. &lt;/p&gt; &lt;p&gt; If &lt;code&gt;LastEvaluatedBackupArn&lt;/code&gt; is not empty, this may or may not indicate that there is more data to be returned. All results are guaranteed to have been returned if and only if no value for &lt;code&gt;LastEvaluatedBackupArn&lt;/code&gt; is returned. &lt;/p&gt;
   * @return lastEvaluatedBackupArn
   */
  @javax.annotation.Nullable
  public String getLastEvaluatedBackupArn() {
    return lastEvaluatedBackupArn;
  }

  public void setLastEvaluatedBackupArn(@javax.annotation.Nullable String lastEvaluatedBackupArn) {
    this.lastEvaluatedBackupArn = lastEvaluatedBackupArn;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListBackupsOutput listBackupsOutput = (ListBackupsOutput) o;
    return Objects.equals(this.backupSummaries, listBackupsOutput.backupSummaries) &&
        Objects.equals(this.lastEvaluatedBackupArn, listBackupsOutput.lastEvaluatedBackupArn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backupSummaries, lastEvaluatedBackupArn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListBackupsOutput {\n");
    sb.append("    backupSummaries: ").append(toIndentedString(backupSummaries)).append("\n");
    sb.append("    lastEvaluatedBackupArn: ").append(toIndentedString(lastEvaluatedBackupArn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("BackupSummaries", "LastEvaluatedBackupArn"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListBackupsOutput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListBackupsOutput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListBackupsOutput is not found in the empty JSON string", ListBackupsOutput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListBackupsOutput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListBackupsOutput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("BackupSummaries") != null && !jsonObj.get("BackupSummaries").isJsonNull()) {
        JsonArray jsonArraybackupSummaries = jsonObj.getAsJsonArray("BackupSummaries");
        if (jsonArraybackupSummaries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("BackupSummaries").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `BackupSummaries` to be an array in the JSON string but got `%s`", jsonObj.get("BackupSummaries").toString()));
          }

          // validate the optional field `BackupSummaries` (array)
          for (int i = 0; i < jsonArraybackupSummaries.size(); i++) {
            BackupSummary.validateJsonElement(jsonArraybackupSummaries.get(i));
          };
        }
      }
      if ((jsonObj.get("LastEvaluatedBackupArn") != null && !jsonObj.get("LastEvaluatedBackupArn").isJsonNull()) && !jsonObj.get("LastEvaluatedBackupArn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `LastEvaluatedBackupArn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("LastEvaluatedBackupArn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListBackupsOutput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListBackupsOutput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListBackupsOutput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListBackupsOutput.class));

       return (TypeAdapter<T>) new TypeAdapter<ListBackupsOutput>() {
           @Override
           public void write(JsonWriter out, ListBackupsOutput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListBackupsOutput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListBackupsOutput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListBackupsOutput
   * @throws IOException if the JSON string is invalid with respect to ListBackupsOutput
   */
  public static ListBackupsOutput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListBackupsOutput.class);
  }

  /**
   * Convert an instance of ListBackupsOutput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

