/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GlobalTable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListGlobalTablesOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:20:21.724079+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ListGlobalTablesOutput {
  public static final String SERIALIZED_NAME_GLOBAL_TABLES = "GlobalTables";
  @SerializedName(SERIALIZED_NAME_GLOBAL_TABLES)
  @javax.annotation.Nullable
  private List<GlobalTable> globalTables;

  public static final String SERIALIZED_NAME_LAST_EVALUATED_GLOBAL_TABLE_NAME = "LastEvaluatedGlobalTableName";
  @SerializedName(SERIALIZED_NAME_LAST_EVALUATED_GLOBAL_TABLE_NAME)
  @javax.annotation.Nullable
  private String lastEvaluatedGlobalTableName;

  public ListGlobalTablesOutput() {
  }

  public ListGlobalTablesOutput globalTables(@javax.annotation.Nullable List<GlobalTable> globalTables) {
    this.globalTables = globalTables;
    return this;
  }

  public ListGlobalTablesOutput addGlobalTablesItem(GlobalTable globalTablesItem) {
    if (this.globalTables == null) {
      this.globalTables = new ArrayList<>();
    }
    this.globalTables.add(globalTablesItem);
    return this;
  }

  /**
   * List of global table names.
   * @return globalTables
   */
  @javax.annotation.Nullable
  public List<GlobalTable> getGlobalTables() {
    return globalTables;
  }

  public void setGlobalTables(@javax.annotation.Nullable List<GlobalTable> globalTables) {
    this.globalTables = globalTables;
  }


  public ListGlobalTablesOutput lastEvaluatedGlobalTableName(@javax.annotation.Nullable String lastEvaluatedGlobalTableName) {
    this.lastEvaluatedGlobalTableName = lastEvaluatedGlobalTableName;
    return this;
  }

  /**
   * Last evaluated global table name.
   * @return lastEvaluatedGlobalTableName
   */
  @javax.annotation.Nullable
  public String getLastEvaluatedGlobalTableName() {
    return lastEvaluatedGlobalTableName;
  }

  public void setLastEvaluatedGlobalTableName(@javax.annotation.Nullable String lastEvaluatedGlobalTableName) {
    this.lastEvaluatedGlobalTableName = lastEvaluatedGlobalTableName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListGlobalTablesOutput listGlobalTablesOutput = (ListGlobalTablesOutput) o;
    return Objects.equals(this.globalTables, listGlobalTablesOutput.globalTables) &&
        Objects.equals(this.lastEvaluatedGlobalTableName, listGlobalTablesOutput.lastEvaluatedGlobalTableName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(globalTables, lastEvaluatedGlobalTableName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListGlobalTablesOutput {\n");
    sb.append("    globalTables: ").append(toIndentedString(globalTables)).append("\n");
    sb.append("    lastEvaluatedGlobalTableName: ").append(toIndentedString(lastEvaluatedGlobalTableName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("GlobalTables", "LastEvaluatedGlobalTableName"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListGlobalTablesOutput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListGlobalTablesOutput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListGlobalTablesOutput is not found in the empty JSON string", ListGlobalTablesOutput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListGlobalTablesOutput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListGlobalTablesOutput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("GlobalTables") != null && !jsonObj.get("GlobalTables").isJsonNull()) {
        JsonArray jsonArrayglobalTables = jsonObj.getAsJsonArray("GlobalTables");
        if (jsonArrayglobalTables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("GlobalTables").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `GlobalTables` to be an array in the JSON string but got `%s`", jsonObj.get("GlobalTables").toString()));
          }

          // validate the optional field `GlobalTables` (array)
          for (int i = 0; i < jsonArrayglobalTables.size(); i++) {
            GlobalTable.validateJsonElement(jsonArrayglobalTables.get(i));
          };
        }
      }
      if ((jsonObj.get("LastEvaluatedGlobalTableName") != null && !jsonObj.get("LastEvaluatedGlobalTableName").isJsonNull()) && !jsonObj.get("LastEvaluatedGlobalTableName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `LastEvaluatedGlobalTableName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("LastEvaluatedGlobalTableName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListGlobalTablesOutput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListGlobalTablesOutput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListGlobalTablesOutput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListGlobalTablesOutput.class));

       return (TypeAdapter<T>) new TypeAdapter<ListGlobalTablesOutput>() {
           @Override
           public void write(JsonWriter out, ListGlobalTablesOutput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListGlobalTablesOutput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListGlobalTablesOutput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListGlobalTablesOutput
   * @throws IOException if the JSON string is invalid with respect to ListGlobalTablesOutput
   */
  public static ListGlobalTablesOutput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListGlobalTablesOutput.class);
  }

  /**
   * Convert an instance of ListGlobalTablesOutput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

