/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AutoScalingSettingsDescription;
import org.openapitools.client.model.BillingModeSummary;
import org.openapitools.client.model.ReplicaGlobalSecondaryIndexSettingsDescription;
import org.openapitools.client.model.ReplicaStatus;
import org.openapitools.client.model.TableClassSummary;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents the properties of a replica.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:20:21.724079+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ReplicaSettingsDescription {
  public static final String SERIALIZED_NAME_REGION_NAME = "RegionName";
  @SerializedName(SERIALIZED_NAME_REGION_NAME)
  @javax.annotation.Nonnull
  private String regionName;

  public static final String SERIALIZED_NAME_REPLICA_STATUS = "ReplicaStatus";
  @SerializedName(SERIALIZED_NAME_REPLICA_STATUS)
  @javax.annotation.Nullable
  private ReplicaStatus replicaStatus;

  public static final String SERIALIZED_NAME_REPLICA_BILLING_MODE_SUMMARY = "ReplicaBillingModeSummary";
  @SerializedName(SERIALIZED_NAME_REPLICA_BILLING_MODE_SUMMARY)
  @javax.annotation.Nullable
  private BillingModeSummary replicaBillingModeSummary;

  public static final String SERIALIZED_NAME_REPLICA_PROVISIONED_READ_CAPACITY_UNITS = "ReplicaProvisionedReadCapacityUnits";
  @SerializedName(SERIALIZED_NAME_REPLICA_PROVISIONED_READ_CAPACITY_UNITS)
  @javax.annotation.Nullable
  private Integer replicaProvisionedReadCapacityUnits;

  public static final String SERIALIZED_NAME_REPLICA_PROVISIONED_READ_CAPACITY_AUTO_SCALING_SETTINGS = "ReplicaProvisionedReadCapacityAutoScalingSettings";
  @SerializedName(SERIALIZED_NAME_REPLICA_PROVISIONED_READ_CAPACITY_AUTO_SCALING_SETTINGS)
  @javax.annotation.Nullable
  private AutoScalingSettingsDescription replicaProvisionedReadCapacityAutoScalingSettings;

  public static final String SERIALIZED_NAME_REPLICA_PROVISIONED_WRITE_CAPACITY_UNITS = "ReplicaProvisionedWriteCapacityUnits";
  @SerializedName(SERIALIZED_NAME_REPLICA_PROVISIONED_WRITE_CAPACITY_UNITS)
  @javax.annotation.Nullable
  private Integer replicaProvisionedWriteCapacityUnits;

  public static final String SERIALIZED_NAME_REPLICA_PROVISIONED_WRITE_CAPACITY_AUTO_SCALING_SETTINGS = "ReplicaProvisionedWriteCapacityAutoScalingSettings";
  @SerializedName(SERIALIZED_NAME_REPLICA_PROVISIONED_WRITE_CAPACITY_AUTO_SCALING_SETTINGS)
  @javax.annotation.Nullable
  private AutoScalingSettingsDescription replicaProvisionedWriteCapacityAutoScalingSettings;

  public static final String SERIALIZED_NAME_REPLICA_GLOBAL_SECONDARY_INDEX_SETTINGS = "ReplicaGlobalSecondaryIndexSettings";
  @SerializedName(SERIALIZED_NAME_REPLICA_GLOBAL_SECONDARY_INDEX_SETTINGS)
  @javax.annotation.Nullable
  private List<ReplicaGlobalSecondaryIndexSettingsDescription> replicaGlobalSecondaryIndexSettings;

  public static final String SERIALIZED_NAME_REPLICA_TABLE_CLASS_SUMMARY = "ReplicaTableClassSummary";
  @SerializedName(SERIALIZED_NAME_REPLICA_TABLE_CLASS_SUMMARY)
  @javax.annotation.Nullable
  private TableClassSummary replicaTableClassSummary;

  public ReplicaSettingsDescription() {
  }

  public ReplicaSettingsDescription regionName(@javax.annotation.Nonnull String regionName) {
    this.regionName = regionName;
    return this;
  }

  /**
   * The Region name of the replica.
   * @return regionName
   */
  @javax.annotation.Nonnull
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(@javax.annotation.Nonnull String regionName) {
    this.regionName = regionName;
  }


  public ReplicaSettingsDescription replicaStatus(@javax.annotation.Nullable ReplicaStatus replicaStatus) {
    this.replicaStatus = replicaStatus;
    return this;
  }

  /**
   * &lt;p&gt;The current state of the Region:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;CREATING&lt;/code&gt; - The Region is being created.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;UPDATING&lt;/code&gt; - The Region is being updated.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;DELETING&lt;/code&gt; - The Region is being deleted.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;ACTIVE&lt;/code&gt; - The Region is ready for use.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
   * @return replicaStatus
   */
  @javax.annotation.Nullable
  public ReplicaStatus getReplicaStatus() {
    return replicaStatus;
  }

  public void setReplicaStatus(@javax.annotation.Nullable ReplicaStatus replicaStatus) {
    this.replicaStatus = replicaStatus;
  }


  public ReplicaSettingsDescription replicaBillingModeSummary(@javax.annotation.Nullable BillingModeSummary replicaBillingModeSummary) {
    this.replicaBillingModeSummary = replicaBillingModeSummary;
    return this;
  }

  /**
   * The read/write capacity mode of the replica.
   * @return replicaBillingModeSummary
   */
  @javax.annotation.Nullable
  public BillingModeSummary getReplicaBillingModeSummary() {
    return replicaBillingModeSummary;
  }

  public void setReplicaBillingModeSummary(@javax.annotation.Nullable BillingModeSummary replicaBillingModeSummary) {
    this.replicaBillingModeSummary = replicaBillingModeSummary;
  }


  public ReplicaSettingsDescription replicaProvisionedReadCapacityUnits(@javax.annotation.Nullable Integer replicaProvisionedReadCapacityUnits) {
    this.replicaProvisionedReadCapacityUnits = replicaProvisionedReadCapacityUnits;
    return this;
  }

  /**
   * The maximum number of strongly consistent reads consumed per second before DynamoDB returns a &lt;code&gt;ThrottlingException&lt;/code&gt;. For more information, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.html#ProvisionedThroughput\&quot;&gt;Specifying Read and Write Requirements&lt;/a&gt; in the &lt;i&gt;Amazon DynamoDB Developer Guide&lt;/i&gt;. 
   * minimum: 0
   * @return replicaProvisionedReadCapacityUnits
   */
  @javax.annotation.Nullable
  public Integer getReplicaProvisionedReadCapacityUnits() {
    return replicaProvisionedReadCapacityUnits;
  }

  public void setReplicaProvisionedReadCapacityUnits(@javax.annotation.Nullable Integer replicaProvisionedReadCapacityUnits) {
    this.replicaProvisionedReadCapacityUnits = replicaProvisionedReadCapacityUnits;
  }


  public ReplicaSettingsDescription replicaProvisionedReadCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedReadCapacityAutoScalingSettings) {
    this.replicaProvisionedReadCapacityAutoScalingSettings = replicaProvisionedReadCapacityAutoScalingSettings;
    return this;
  }

  /**
   * Auto scaling settings for a global table replica&#39;s read capacity units.
   * @return replicaProvisionedReadCapacityAutoScalingSettings
   */
  @javax.annotation.Nullable
  public AutoScalingSettingsDescription getReplicaProvisionedReadCapacityAutoScalingSettings() {
    return replicaProvisionedReadCapacityAutoScalingSettings;
  }

  public void setReplicaProvisionedReadCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedReadCapacityAutoScalingSettings) {
    this.replicaProvisionedReadCapacityAutoScalingSettings = replicaProvisionedReadCapacityAutoScalingSettings;
  }


  public ReplicaSettingsDescription replicaProvisionedWriteCapacityUnits(@javax.annotation.Nullable Integer replicaProvisionedWriteCapacityUnits) {
    this.replicaProvisionedWriteCapacityUnits = replicaProvisionedWriteCapacityUnits;
    return this;
  }

  /**
   * The maximum number of writes consumed per second before DynamoDB returns a &lt;code&gt;ThrottlingException&lt;/code&gt;. For more information, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.html#ProvisionedThroughput\&quot;&gt;Specifying Read and Write Requirements&lt;/a&gt; in the &lt;i&gt;Amazon DynamoDB Developer Guide&lt;/i&gt;.
   * minimum: 0
   * @return replicaProvisionedWriteCapacityUnits
   */
  @javax.annotation.Nullable
  public Integer getReplicaProvisionedWriteCapacityUnits() {
    return replicaProvisionedWriteCapacityUnits;
  }

  public void setReplicaProvisionedWriteCapacityUnits(@javax.annotation.Nullable Integer replicaProvisionedWriteCapacityUnits) {
    this.replicaProvisionedWriteCapacityUnits = replicaProvisionedWriteCapacityUnits;
  }


  public ReplicaSettingsDescription replicaProvisionedWriteCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedWriteCapacityAutoScalingSettings) {
    this.replicaProvisionedWriteCapacityAutoScalingSettings = replicaProvisionedWriteCapacityAutoScalingSettings;
    return this;
  }

  /**
   * Auto scaling settings for a global table replica&#39;s write capacity units.
   * @return replicaProvisionedWriteCapacityAutoScalingSettings
   */
  @javax.annotation.Nullable
  public AutoScalingSettingsDescription getReplicaProvisionedWriteCapacityAutoScalingSettings() {
    return replicaProvisionedWriteCapacityAutoScalingSettings;
  }

  public void setReplicaProvisionedWriteCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedWriteCapacityAutoScalingSettings) {
    this.replicaProvisionedWriteCapacityAutoScalingSettings = replicaProvisionedWriteCapacityAutoScalingSettings;
  }


  public ReplicaSettingsDescription replicaGlobalSecondaryIndexSettings(@javax.annotation.Nullable List<ReplicaGlobalSecondaryIndexSettingsDescription> replicaGlobalSecondaryIndexSettings) {
    this.replicaGlobalSecondaryIndexSettings = replicaGlobalSecondaryIndexSettings;
    return this;
  }

  public ReplicaSettingsDescription addReplicaGlobalSecondaryIndexSettingsItem(ReplicaGlobalSecondaryIndexSettingsDescription replicaGlobalSecondaryIndexSettingsItem) {
    if (this.replicaGlobalSecondaryIndexSettings == null) {
      this.replicaGlobalSecondaryIndexSettings = new ArrayList<>();
    }
    this.replicaGlobalSecondaryIndexSettings.add(replicaGlobalSecondaryIndexSettingsItem);
    return this;
  }

  /**
   * Replica global secondary index settings for the global table.
   * @return replicaGlobalSecondaryIndexSettings
   */
  @javax.annotation.Nullable
  public List<ReplicaGlobalSecondaryIndexSettingsDescription> getReplicaGlobalSecondaryIndexSettings() {
    return replicaGlobalSecondaryIndexSettings;
  }

  public void setReplicaGlobalSecondaryIndexSettings(@javax.annotation.Nullable List<ReplicaGlobalSecondaryIndexSettingsDescription> replicaGlobalSecondaryIndexSettings) {
    this.replicaGlobalSecondaryIndexSettings = replicaGlobalSecondaryIndexSettings;
  }


  public ReplicaSettingsDescription replicaTableClassSummary(@javax.annotation.Nullable TableClassSummary replicaTableClassSummary) {
    this.replicaTableClassSummary = replicaTableClassSummary;
    return this;
  }

  /**
   * Get replicaTableClassSummary
   * @return replicaTableClassSummary
   */
  @javax.annotation.Nullable
  public TableClassSummary getReplicaTableClassSummary() {
    return replicaTableClassSummary;
  }

  public void setReplicaTableClassSummary(@javax.annotation.Nullable TableClassSummary replicaTableClassSummary) {
    this.replicaTableClassSummary = replicaTableClassSummary;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplicaSettingsDescription replicaSettingsDescription = (ReplicaSettingsDescription) o;
    return Objects.equals(this.regionName, replicaSettingsDescription.regionName) &&
        Objects.equals(this.replicaStatus, replicaSettingsDescription.replicaStatus) &&
        Objects.equals(this.replicaBillingModeSummary, replicaSettingsDescription.replicaBillingModeSummary) &&
        Objects.equals(this.replicaProvisionedReadCapacityUnits, replicaSettingsDescription.replicaProvisionedReadCapacityUnits) &&
        Objects.equals(this.replicaProvisionedReadCapacityAutoScalingSettings, replicaSettingsDescription.replicaProvisionedReadCapacityAutoScalingSettings) &&
        Objects.equals(this.replicaProvisionedWriteCapacityUnits, replicaSettingsDescription.replicaProvisionedWriteCapacityUnits) &&
        Objects.equals(this.replicaProvisionedWriteCapacityAutoScalingSettings, replicaSettingsDescription.replicaProvisionedWriteCapacityAutoScalingSettings) &&
        Objects.equals(this.replicaGlobalSecondaryIndexSettings, replicaSettingsDescription.replicaGlobalSecondaryIndexSettings) &&
        Objects.equals(this.replicaTableClassSummary, replicaSettingsDescription.replicaTableClassSummary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionName, replicaStatus, replicaBillingModeSummary, replicaProvisionedReadCapacityUnits, replicaProvisionedReadCapacityAutoScalingSettings, replicaProvisionedWriteCapacityUnits, replicaProvisionedWriteCapacityAutoScalingSettings, replicaGlobalSecondaryIndexSettings, replicaTableClassSummary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplicaSettingsDescription {\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    replicaStatus: ").append(toIndentedString(replicaStatus)).append("\n");
    sb.append("    replicaBillingModeSummary: ").append(toIndentedString(replicaBillingModeSummary)).append("\n");
    sb.append("    replicaProvisionedReadCapacityUnits: ").append(toIndentedString(replicaProvisionedReadCapacityUnits)).append("\n");
    sb.append("    replicaProvisionedReadCapacityAutoScalingSettings: ").append(toIndentedString(replicaProvisionedReadCapacityAutoScalingSettings)).append("\n");
    sb.append("    replicaProvisionedWriteCapacityUnits: ").append(toIndentedString(replicaProvisionedWriteCapacityUnits)).append("\n");
    sb.append("    replicaProvisionedWriteCapacityAutoScalingSettings: ").append(toIndentedString(replicaProvisionedWriteCapacityAutoScalingSettings)).append("\n");
    sb.append("    replicaGlobalSecondaryIndexSettings: ").append(toIndentedString(replicaGlobalSecondaryIndexSettings)).append("\n");
    sb.append("    replicaTableClassSummary: ").append(toIndentedString(replicaTableClassSummary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("RegionName", "ReplicaStatus", "ReplicaBillingModeSummary", "ReplicaProvisionedReadCapacityUnits", "ReplicaProvisionedReadCapacityAutoScalingSettings", "ReplicaProvisionedWriteCapacityUnits", "ReplicaProvisionedWriteCapacityAutoScalingSettings", "ReplicaGlobalSecondaryIndexSettings", "ReplicaTableClassSummary"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("RegionName"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReplicaSettingsDescription
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReplicaSettingsDescription.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReplicaSettingsDescription is not found in the empty JSON string", ReplicaSettingsDescription.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReplicaSettingsDescription.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReplicaSettingsDescription` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReplicaSettingsDescription.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("RegionName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RegionName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RegionName").toString()));
      }
      // validate the optional field `ReplicaStatus`
      if (jsonObj.get("ReplicaStatus") != null && !jsonObj.get("ReplicaStatus").isJsonNull()) {
        ReplicaStatus.validateJsonElement(jsonObj.get("ReplicaStatus"));
      }
      // validate the optional field `ReplicaBillingModeSummary`
      if (jsonObj.get("ReplicaBillingModeSummary") != null && !jsonObj.get("ReplicaBillingModeSummary").isJsonNull()) {
        BillingModeSummary.validateJsonElement(jsonObj.get("ReplicaBillingModeSummary"));
      }
      // validate the optional field `ReplicaProvisionedReadCapacityAutoScalingSettings`
      if (jsonObj.get("ReplicaProvisionedReadCapacityAutoScalingSettings") != null && !jsonObj.get("ReplicaProvisionedReadCapacityAutoScalingSettings").isJsonNull()) {
        AutoScalingSettingsDescription.validateJsonElement(jsonObj.get("ReplicaProvisionedReadCapacityAutoScalingSettings"));
      }
      // validate the optional field `ReplicaProvisionedWriteCapacityAutoScalingSettings`
      if (jsonObj.get("ReplicaProvisionedWriteCapacityAutoScalingSettings") != null && !jsonObj.get("ReplicaProvisionedWriteCapacityAutoScalingSettings").isJsonNull()) {
        AutoScalingSettingsDescription.validateJsonElement(jsonObj.get("ReplicaProvisionedWriteCapacityAutoScalingSettings"));
      }
      if (jsonObj.get("ReplicaGlobalSecondaryIndexSettings") != null && !jsonObj.get("ReplicaGlobalSecondaryIndexSettings").isJsonNull()) {
        JsonArray jsonArrayreplicaGlobalSecondaryIndexSettings = jsonObj.getAsJsonArray("ReplicaGlobalSecondaryIndexSettings");
        if (jsonArrayreplicaGlobalSecondaryIndexSettings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ReplicaGlobalSecondaryIndexSettings").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ReplicaGlobalSecondaryIndexSettings` to be an array in the JSON string but got `%s`", jsonObj.get("ReplicaGlobalSecondaryIndexSettings").toString()));
          }

          // validate the optional field `ReplicaGlobalSecondaryIndexSettings` (array)
          for (int i = 0; i < jsonArrayreplicaGlobalSecondaryIndexSettings.size(); i++) {
            ReplicaGlobalSecondaryIndexSettingsDescription.validateJsonElement(jsonArrayreplicaGlobalSecondaryIndexSettings.get(i));
          };
        }
      }
      // validate the optional field `ReplicaTableClassSummary`
      if (jsonObj.get("ReplicaTableClassSummary") != null && !jsonObj.get("ReplicaTableClassSummary").isJsonNull()) {
        TableClassSummary.validateJsonElement(jsonObj.get("ReplicaTableClassSummary"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReplicaSettingsDescription.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReplicaSettingsDescription' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReplicaSettingsDescription> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReplicaSettingsDescription.class));

       return (TypeAdapter<T>) new TypeAdapter<ReplicaSettingsDescription>() {
           @Override
           public void write(JsonWriter out, ReplicaSettingsDescription value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReplicaSettingsDescription read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReplicaSettingsDescription given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReplicaSettingsDescription
   * @throws IOException if the JSON string is invalid with respect to ReplicaSettingsDescription
   */
  public static ReplicaSettingsDescription fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReplicaSettingsDescription.class);
  }

  /**
   * Convert an instance of ReplicaSettingsDescription to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

