/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AutoScalingSettingsDescription;
import org.openapitools.client.model.ReplicaGlobalSecondaryIndexAutoScalingDescription;
import org.openapitools.client.model.ReplicaStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents the auto scaling settings of the replica.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:20:21.724079+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ReplicaAutoScalingDescription {
  public static final String SERIALIZED_NAME_REGION_NAME = "RegionName";
  @SerializedName(SERIALIZED_NAME_REGION_NAME)
  @javax.annotation.Nullable
  private String regionName;

  public static final String SERIALIZED_NAME_GLOBAL_SECONDARY_INDEXES = "GlobalSecondaryIndexes";
  @SerializedName(SERIALIZED_NAME_GLOBAL_SECONDARY_INDEXES)
  @javax.annotation.Nullable
  private List<ReplicaGlobalSecondaryIndexAutoScalingDescription> globalSecondaryIndexes;

  public static final String SERIALIZED_NAME_REPLICA_PROVISIONED_READ_CAPACITY_AUTO_SCALING_SETTINGS = "ReplicaProvisionedReadCapacityAutoScalingSettings";
  @SerializedName(SERIALIZED_NAME_REPLICA_PROVISIONED_READ_CAPACITY_AUTO_SCALING_SETTINGS)
  @javax.annotation.Nullable
  private AutoScalingSettingsDescription replicaProvisionedReadCapacityAutoScalingSettings;

  public static final String SERIALIZED_NAME_REPLICA_PROVISIONED_WRITE_CAPACITY_AUTO_SCALING_SETTINGS = "ReplicaProvisionedWriteCapacityAutoScalingSettings";
  @SerializedName(SERIALIZED_NAME_REPLICA_PROVISIONED_WRITE_CAPACITY_AUTO_SCALING_SETTINGS)
  @javax.annotation.Nullable
  private AutoScalingSettingsDescription replicaProvisionedWriteCapacityAutoScalingSettings;

  public static final String SERIALIZED_NAME_REPLICA_STATUS = "ReplicaStatus";
  @SerializedName(SERIALIZED_NAME_REPLICA_STATUS)
  @javax.annotation.Nullable
  private ReplicaStatus replicaStatus;

  public ReplicaAutoScalingDescription() {
  }

  public ReplicaAutoScalingDescription regionName(@javax.annotation.Nullable String regionName) {
    this.regionName = regionName;
    return this;
  }

  /**
   * The Region where the replica exists.
   * @return regionName
   */
  @javax.annotation.Nullable
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(@javax.annotation.Nullable String regionName) {
    this.regionName = regionName;
  }


  public ReplicaAutoScalingDescription globalSecondaryIndexes(@javax.annotation.Nullable List<ReplicaGlobalSecondaryIndexAutoScalingDescription> globalSecondaryIndexes) {
    this.globalSecondaryIndexes = globalSecondaryIndexes;
    return this;
  }

  public ReplicaAutoScalingDescription addGlobalSecondaryIndexesItem(ReplicaGlobalSecondaryIndexAutoScalingDescription globalSecondaryIndexesItem) {
    if (this.globalSecondaryIndexes == null) {
      this.globalSecondaryIndexes = new ArrayList<>();
    }
    this.globalSecondaryIndexes.add(globalSecondaryIndexesItem);
    return this;
  }

  /**
   * Replica-specific global secondary index auto scaling settings.
   * @return globalSecondaryIndexes
   */
  @javax.annotation.Nullable
  public List<ReplicaGlobalSecondaryIndexAutoScalingDescription> getGlobalSecondaryIndexes() {
    return globalSecondaryIndexes;
  }

  public void setGlobalSecondaryIndexes(@javax.annotation.Nullable List<ReplicaGlobalSecondaryIndexAutoScalingDescription> globalSecondaryIndexes) {
    this.globalSecondaryIndexes = globalSecondaryIndexes;
  }


  public ReplicaAutoScalingDescription replicaProvisionedReadCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedReadCapacityAutoScalingSettings) {
    this.replicaProvisionedReadCapacityAutoScalingSettings = replicaProvisionedReadCapacityAutoScalingSettings;
    return this;
  }

  /**
   * Get replicaProvisionedReadCapacityAutoScalingSettings
   * @return replicaProvisionedReadCapacityAutoScalingSettings
   */
  @javax.annotation.Nullable
  public AutoScalingSettingsDescription getReplicaProvisionedReadCapacityAutoScalingSettings() {
    return replicaProvisionedReadCapacityAutoScalingSettings;
  }

  public void setReplicaProvisionedReadCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedReadCapacityAutoScalingSettings) {
    this.replicaProvisionedReadCapacityAutoScalingSettings = replicaProvisionedReadCapacityAutoScalingSettings;
  }


  public ReplicaAutoScalingDescription replicaProvisionedWriteCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedWriteCapacityAutoScalingSettings) {
    this.replicaProvisionedWriteCapacityAutoScalingSettings = replicaProvisionedWriteCapacityAutoScalingSettings;
    return this;
  }

  /**
   * Get replicaProvisionedWriteCapacityAutoScalingSettings
   * @return replicaProvisionedWriteCapacityAutoScalingSettings
   */
  @javax.annotation.Nullable
  public AutoScalingSettingsDescription getReplicaProvisionedWriteCapacityAutoScalingSettings() {
    return replicaProvisionedWriteCapacityAutoScalingSettings;
  }

  public void setReplicaProvisionedWriteCapacityAutoScalingSettings(@javax.annotation.Nullable AutoScalingSettingsDescription replicaProvisionedWriteCapacityAutoScalingSettings) {
    this.replicaProvisionedWriteCapacityAutoScalingSettings = replicaProvisionedWriteCapacityAutoScalingSettings;
  }


  public ReplicaAutoScalingDescription replicaStatus(@javax.annotation.Nullable ReplicaStatus replicaStatus) {
    this.replicaStatus = replicaStatus;
    return this;
  }

  /**
   * &lt;p&gt;The current state of the replica:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;CREATING&lt;/code&gt; - The replica is being created.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;UPDATING&lt;/code&gt; - The replica is being updated.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;DELETING&lt;/code&gt; - The replica is being deleted.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;ACTIVE&lt;/code&gt; - The replica is ready for use.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
   * @return replicaStatus
   */
  @javax.annotation.Nullable
  public ReplicaStatus getReplicaStatus() {
    return replicaStatus;
  }

  public void setReplicaStatus(@javax.annotation.Nullable ReplicaStatus replicaStatus) {
    this.replicaStatus = replicaStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplicaAutoScalingDescription replicaAutoScalingDescription = (ReplicaAutoScalingDescription) o;
    return Objects.equals(this.regionName, replicaAutoScalingDescription.regionName) &&
        Objects.equals(this.globalSecondaryIndexes, replicaAutoScalingDescription.globalSecondaryIndexes) &&
        Objects.equals(this.replicaProvisionedReadCapacityAutoScalingSettings, replicaAutoScalingDescription.replicaProvisionedReadCapacityAutoScalingSettings) &&
        Objects.equals(this.replicaProvisionedWriteCapacityAutoScalingSettings, replicaAutoScalingDescription.replicaProvisionedWriteCapacityAutoScalingSettings) &&
        Objects.equals(this.replicaStatus, replicaAutoScalingDescription.replicaStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionName, globalSecondaryIndexes, replicaProvisionedReadCapacityAutoScalingSettings, replicaProvisionedWriteCapacityAutoScalingSettings, replicaStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplicaAutoScalingDescription {\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    globalSecondaryIndexes: ").append(toIndentedString(globalSecondaryIndexes)).append("\n");
    sb.append("    replicaProvisionedReadCapacityAutoScalingSettings: ").append(toIndentedString(replicaProvisionedReadCapacityAutoScalingSettings)).append("\n");
    sb.append("    replicaProvisionedWriteCapacityAutoScalingSettings: ").append(toIndentedString(replicaProvisionedWriteCapacityAutoScalingSettings)).append("\n");
    sb.append("    replicaStatus: ").append(toIndentedString(replicaStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("RegionName", "GlobalSecondaryIndexes", "ReplicaProvisionedReadCapacityAutoScalingSettings", "ReplicaProvisionedWriteCapacityAutoScalingSettings", "ReplicaStatus"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReplicaAutoScalingDescription
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReplicaAutoScalingDescription.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReplicaAutoScalingDescription is not found in the empty JSON string", ReplicaAutoScalingDescription.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReplicaAutoScalingDescription.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReplicaAutoScalingDescription` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("RegionName") != null && !jsonObj.get("RegionName").isJsonNull()) && !jsonObj.get("RegionName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RegionName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RegionName").toString()));
      }
      if (jsonObj.get("GlobalSecondaryIndexes") != null && !jsonObj.get("GlobalSecondaryIndexes").isJsonNull()) {
        JsonArray jsonArrayglobalSecondaryIndexes = jsonObj.getAsJsonArray("GlobalSecondaryIndexes");
        if (jsonArrayglobalSecondaryIndexes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("GlobalSecondaryIndexes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `GlobalSecondaryIndexes` to be an array in the JSON string but got `%s`", jsonObj.get("GlobalSecondaryIndexes").toString()));
          }

          // validate the optional field `GlobalSecondaryIndexes` (array)
          for (int i = 0; i < jsonArrayglobalSecondaryIndexes.size(); i++) {
            ReplicaGlobalSecondaryIndexAutoScalingDescription.validateJsonElement(jsonArrayglobalSecondaryIndexes.get(i));
          };
        }
      }
      // validate the optional field `ReplicaProvisionedReadCapacityAutoScalingSettings`
      if (jsonObj.get("ReplicaProvisionedReadCapacityAutoScalingSettings") != null && !jsonObj.get("ReplicaProvisionedReadCapacityAutoScalingSettings").isJsonNull()) {
        AutoScalingSettingsDescription.validateJsonElement(jsonObj.get("ReplicaProvisionedReadCapacityAutoScalingSettings"));
      }
      // validate the optional field `ReplicaProvisionedWriteCapacityAutoScalingSettings`
      if (jsonObj.get("ReplicaProvisionedWriteCapacityAutoScalingSettings") != null && !jsonObj.get("ReplicaProvisionedWriteCapacityAutoScalingSettings").isJsonNull()) {
        AutoScalingSettingsDescription.validateJsonElement(jsonObj.get("ReplicaProvisionedWriteCapacityAutoScalingSettings"));
      }
      // validate the optional field `ReplicaStatus`
      if (jsonObj.get("ReplicaStatus") != null && !jsonObj.get("ReplicaStatus").isJsonNull()) {
        ReplicaStatus.validateJsonElement(jsonObj.get("ReplicaStatus"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReplicaAutoScalingDescription.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReplicaAutoScalingDescription' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReplicaAutoScalingDescription> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReplicaAutoScalingDescription.class));

       return (TypeAdapter<T>) new TypeAdapter<ReplicaAutoScalingDescription>() {
           @Override
           public void write(JsonWriter out, ReplicaAutoScalingDescription value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReplicaAutoScalingDescription read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReplicaAutoScalingDescription given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReplicaAutoScalingDescription
   * @throws IOException if the JSON string is invalid with respect to ReplicaAutoScalingDescription
   */
  public static ReplicaAutoScalingDescription fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReplicaAutoScalingDescription.class);
  }

  /**
   * Convert an instance of ReplicaAutoScalingDescription to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

