/*
 * Amazon DynamoDB
 * <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability. DynamoDB lets you offload the administrative burdens of operating and scaling a distributed database, so that you don't have to worry about hardware provisioning, setup and configuration, replication, software patching, or cluster scaling.</p> <p>With DynamoDB, you can create database tables that can store and retrieve any amount of data, and serve any level of request traffic. You can scale up or scale down your tables' throughput capacity without downtime or performance degradation, and use the Amazon Web Services Management Console to monitor resource utilization and performance metrics.</p> <p>DynamoDB automatically spreads the data and traffic for your tables over a sufficient number of servers to handle your throughput and storage requirements, while maintaining consistent and fast performance. All of your data is stored on solid state disks (SSDs) and automatically replicated across multiple Availability Zones in an Amazon Web Services Region, providing built-in high availability and data durability.</p>
 *
 * The version of the OpenAPI document: 2012-08-10
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.TableClass;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Contains details of the table class.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:20:21.724079+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class TableClassSummary {
  public static final String SERIALIZED_NAME_TABLE_CLASS = "TableClass";
  @SerializedName(SERIALIZED_NAME_TABLE_CLASS)
  @javax.annotation.Nullable
  private TableClass tableClass;

  public static final String SERIALIZED_NAME_LAST_UPDATE_DATE_TIME = "LastUpdateDateTime";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATE_DATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdateDateTime;

  public TableClassSummary() {
  }

  public TableClassSummary tableClass(@javax.annotation.Nullable TableClass tableClass) {
    this.tableClass = tableClass;
    return this;
  }

  /**
   * The table class of the specified table. Valid values are &lt;code&gt;STANDARD&lt;/code&gt; and &lt;code&gt;STANDARD_INFREQUENT_ACCESS&lt;/code&gt;.
   * @return tableClass
   */
  @javax.annotation.Nullable
  public TableClass getTableClass() {
    return tableClass;
  }

  public void setTableClass(@javax.annotation.Nullable TableClass tableClass) {
    this.tableClass = tableClass;
  }


  public TableClassSummary lastUpdateDateTime(@javax.annotation.Nullable OffsetDateTime lastUpdateDateTime) {
    this.lastUpdateDateTime = lastUpdateDateTime;
    return this;
  }

  /**
   * The date and time at which the table class was last updated.
   * @return lastUpdateDateTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastUpdateDateTime() {
    return lastUpdateDateTime;
  }

  public void setLastUpdateDateTime(@javax.annotation.Nullable OffsetDateTime lastUpdateDateTime) {
    this.lastUpdateDateTime = lastUpdateDateTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TableClassSummary tableClassSummary = (TableClassSummary) o;
    return Objects.equals(this.tableClass, tableClassSummary.tableClass) &&
        Objects.equals(this.lastUpdateDateTime, tableClassSummary.lastUpdateDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tableClass, lastUpdateDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TableClassSummary {\n");
    sb.append("    tableClass: ").append(toIndentedString(tableClass)).append("\n");
    sb.append("    lastUpdateDateTime: ").append(toIndentedString(lastUpdateDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("TableClass", "LastUpdateDateTime"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TableClassSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TableClassSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TableClassSummary is not found in the empty JSON string", TableClassSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TableClassSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TableClassSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `TableClass`
      if (jsonObj.get("TableClass") != null && !jsonObj.get("TableClass").isJsonNull()) {
        TableClass.validateJsonElement(jsonObj.get("TableClass"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TableClassSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TableClassSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TableClassSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TableClassSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<TableClassSummary>() {
           @Override
           public void write(JsonWriter out, TableClassSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TableClassSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TableClassSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TableClassSummary
   * @throws IOException if the JSON string is invalid with respect to TableClassSummary
   */
  public static TableClassSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TableClassSummary.class);
  }

  /**
   * Convert an instance of TableClassSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

